CREATE TABLE EXPENSE_INFO
(
    ID         BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    AMOUNT     DOUBLE                NOT NULL,
    TIME_STAMP DATETIME,
    USER_ID    BIGINT                NOT NULL,
    CATEGORY_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE USER
(
    ID   BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255)          NOT NULL
)

CREATE TABLE CATEGORY
(
    CATEGORY_ID VARCHAR(255) PRIMARY KEY,
    LABEL       VARCHAR(255),
    COLOR       VARCHAR(255)
)
